print("enter your school name")
schoolname=input()
print("enter your school address")
schooladdress=input()
print("enter your school number")
schoolnumber=input()
print("enter your school email")
schoolemail=input()
print("these are my details " , schoolname , schooladdress , schoolnumber , schoolemail)
